# Generated by Django 2.2.12 on 2020-05-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosuser',
            options={'verbose_name': 'Datos de Usuario', 'verbose_name_plural': 'Información'},
        ),
        migrations.AlterModelOptions(
            name='detaroles',
            options={'verbose_name': 'Roles de Usuario', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='habiluser',
            options={'verbose_name': 'Habilidades del Usuario', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Nivel de Habilidad', 'verbose_name_plural': 'Niveles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='habiluser',
            name='DescHabil',
            field=models.TextField(verbose_name='Descripción de la Habilidad'),
        ),
    ]
