# Generated by Django 2.2.12 on 2020-05-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0006_auto_20200514_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoproy', models.CharField(max_length=100, verbose_name='Tipo de proyecto')),
                ('lenguaje', models.CharField(max_length=50, verbose_name='Lenguaje Back-End')),
                ('motordb', models.CharField(max_length=50, verbose_name='Motor BD')),
                ('arquitect', models.CharField(max_length=150, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria de proyecto',
                'verbose_name_plural': 'Tipo de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombtido', models.CharField(max_length=50, verbose_name='Nombre de tipo de documento')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categoría de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombproyect', models.CharField(max_length=256, verbose_name='Nombre de Proyecto')),
                ('descproyect', models.TextField(verbose_name='Descripción del proyecto')),
                ('logoproyect', models.ImageField(upload_to='img/proyectos', verbose_name='Icono')),
                ('fechaini', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha de Finalización')),
                ('urlrepo', models.URLField(verbose_name='Enlace de repositorio')),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CateProyecto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Proyectos de usuario',
                'verbose_name_plural': 'Proyectos y Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombdocu', models.CharField(max_length=256, verbose_name='Nombre de Documento')),
                ('documento', models.FileField(upload_to='documentos/proyectos', verbose_name='Archivo')),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos')),
                ('idtipodocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Categoría')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Documentos de Proyecto',
                'verbose_name_plural': 'Documentos de Proyecto',
            },
        ),
    ]
